# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='specifices',
            new_name='specifics',
        ),
    ]
